[TEMP]msm8996-common: disable DEXPREOPT
* dunno what caused it suddenly but until then disable this

ERROR: Dex2oat failed to compile a boot image.
It is likely that the boot classpath is inconsistent.
Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier
to see verification errors.

Change-Id: Id1ac34c4b1f75e764d0548f4287bdf610b2d866f